### ISSUE TITLE
search for a task by typing keywords into a search box

### ISSUE THREAD

**Issue by ymll** [cs2103jan2015-t10-2j/main#1]
so that the user can find the task quickly

**Comment by anshumanmohan** [comment]
can find tasks efficiently, thereby saving time

**Comment by ymll** [comment]
Return the task name instead of ID only

**Comment by anshumanmohan** [comment]
Return the task name and the FAKE ID instead of the whole ID. Refer to #56  and #57.

**Comment by anshumanmohan** [comment]
This has been implemented already.
