### ISSUE TITLE
schedule "recurring tasks", that the program automatically adds to the calendar based on some user-set frequency

### ISSUE THREAD

**Issue by ymll** [cs2103jan2015-t10-2j/main#13]
so that the user don't have to create the same tasks again

**Comment by jerace23** [comment]
So that i can save time on other things

**Comment by anshumanmohan** [comment]
avoid manually scheduling similar tasks repeatedly, thereby saving time

**Comment by anshumanmohan** [comment]
Please break down into tasks as needed.

**Comment by anshumanmohan** [comment]
Closing this temporarily. We shall do this if, by some miracle, we have a lot of time.
