### ISSUE TITLE
swap schedules or tasks quickly ???????

### ISSUE THREAD

**Issue by ymll** [cs2103jan2015-t10-2j/main#14]
so that the user do not have to spend time deleting and creating the same tasks or schedules again

**Comment by anshumanmohan** [comment]
save time, in stead of deleting and creating the same tasks repeatedly.
(GUYS, I DON'T REALLY UNDERSTAND THIS ONE, HAHA)

**Comment by anshumanmohan** [comment]
temporarily closing this because it is not compulsory...
