### ISSUE TITLE
synchronise the tasks to Google Calendar (or similar third party software)

### ISSUE THREAD

**Issue by ymll** [cs2103jan2015-t10-2j/main#17]
so that I can use the functions provided by Google too

**Comment by jerace23** [comment]
So that the user access the task on mutilple locations

**Comment by anshumanmohan** [comment]
access my tasks across various platforms, and make changes on the fly using features offered by, say, Google.

**Comment by anshumanmohan** [comment]
temporarily closing this because it is not compulsory...
