### ISSUE TITLE
search for empty slots with filters on attributes (e.g. start time, end time)

### ISSUE THREAD

**Issue by ymll** [cs2103jan2015-t10-2j/main#18]
so that the user can easily arrange a time period to a new task

**Comment by anshumanmohan** [comment]
easily find suitable time slots in which to schedule new tasks

**Comment by jerace23** [comment]
close #18

**Comment by anshumanmohan** [comment]
Jerome said he wants to do this. 
As discussed in class today, you can assume that he sleeps from 00:00 to 5:00. Then this feature will become easier. Accept a time length, (e.g. 2 hours, 1 hour, 3 hours) and find all slots that are at least that long.
