### ISSUE TITLE
create common tasks with a simple command (quick add function)

### ISSUE THREAD

**Issue by ymll** [cs2103jan2015-t10-2j/main#19]
so that the user can simply input the task with one line

**Comment by jerace23** [comment]
So that the user can minimize the no. of keystrokes.

**Comment by anshumanmohan** [comment]
perform commonplace scheduling with fewer keystrokes

**Comment by anshumanmohan** [comment]
Who did the AddCommandHandler? Can the same person please self-assign to this issue?
@ymll @jerace23

**Comment by anshumanmohan** [comment]
This will be handled automatically once we allow for natural language (#59), and optional inputs (#73)
