### ISSUE TITLE
expect to see hints or feedback from the program when typing commands (esp when the user makes a mistake)

### ISSUE THREAD

**Issue by ymll** [cs2103jan2015-t10-2j/main#21]
so that the user can learn the command and know how to use the software in an ease way.

**Comment by jerace23** [comment]
So that the user does not have to look at the manual oftenly.

**Comment by anshumanmohan** [comment]
can learn more efficient ways to use the program, and avoid referring to the manual too often

**Comment by anshumanmohan** [comment]
This is the same as #82. Closing...
