### ISSUE TITLE
view my tasks for different time scales ( e.g. "week view", "month view")

### ISSUE THREAD

**Issue by ymll** [cs2103jan2015-t10-2j/main#31]
so that they can show the task in an more organised way

**Comment by jerace23** [comment]
So that they can have an overview of tasks

**Comment by anshumanmohan** [comment]
have an overview of the tasks

**Comment by ymll** [comment]
Change the display function according to the V0.0 Manual

**Comment by anshumanmohan** [comment]
Team discussion is needed here. Shall we make the user enter something like "view week" or "view month"? How will the user go to the NEXT week/month?

An idea:
A
1. User enters "view week".
2. By default, the current week comes up. Let's say five items are scheduled for the week. Then there is an option that says "to view next week, hit n". "to switch to month view, hit m".

B
1. User enters "month view".
2. The current month comes up. An option is present to view the next month. An option is also present to "quickly switch to week view". For example: "to zoom into week 1, hit w1. to zoom into week 3, hit w3."

**Comment by jerace23** [comment]
Option A will be good because its straight forward. Option B will be a little bit difficult to the user because if he/or she wants to view tasks on a particular week which is somewhere around the middle of the year, they will be spending quite a amount of time to think which week is that(e.g week 49) after going through manually in the calendar or guessing through.

**Comment by jerace23** [comment]
Sorry I deleted my earlier comment as I overlooked option B. I will now favor option B as it would be much more simpler to use. If the User wants to view tasks on a particular month, he or she can hit that month number. And as month has 4 weeks, they can zoom into their weeks up to week 4. They can also continue view next month by hitting n, and continue the same process again!

**Comment by ymll** [comment]
I have another suggestion:
enter "view week", show the current week
enter "view month", show the current month
enter "view week 18/3/15", show the week of 18/3/15
or enter "view week 3 of April"
I think it is more easy to use if we support short natural language

And we can still show the next week as idea A does, what do u think?

**Comment by jerace23** [comment]
@ ymll. if year doesn't matter, then we can use week 3 of April. But what if there is a user who wants to view tasks next year? (for e.g marriage preparations). Anyway this idea is still good but need to consider some of these factors. For Idea A, if the user wants to view task say week 49 from week 11, does he always have to hit n? Can I assume that he can still type the same command "view week 30/11/15" for week 49?

**Comment by ymll** [comment]
@jerace23 How about:
if the year is not given, treat it as this year as default
I think it would be better if we can support all different kinds of view with the same command

**Comment by jerace23** [comment]
@ymll. Oh so if that is the case, the program can accept two natural languages. For e.g. view week 18/3/15 or view week 3 of April for current year. I am alright with Lily's suggestion!

**Comment by ymll** [comment]
and for day view:
"view 15/3/15" -> show the day view of 15 Mar
we can improve the date entering later, but at this point, it would be better if we can have the displaying function first.
To improve, we can support the natural language like "view today" or "view tomorrow". 

parse the input is another job and we can separate it into another issue.
you can first create a java class receiving a date and the type of view (day/week/month), which can display the tasks accordingly.

Is it okay for it?

**Comment by jerace23** [comment]
Yes its ok!:)  Can I still use the CalendarView Class instead of creating a new java class? Do you want to use Idea A in it?
Will improving on natural language be on the next milestone?

**Comment by anshumanmohan** [comment]
I'm creating a new issue as "enhancement", which allows for natural language throughout the program. As Lily points out, natural language is quite important for the final project. However, let's not worry about it too much right now.
For V0.2, let's just allow 
"view today"
"view tomorrow"
"view week" (shows current week and gives options for Prev and Next)
"view month" (shows current month and gives options for P and N)  
"view year" (shows current year and gives options for P and N)

**Comment by anshumanmohan** [comment]
@jerace23 , yo if you want to improve this, please do. If not, please close. :)
