### ISSUE TITLE
receive a summary of the day every morning

### ISSUE THREAD

**Issue by ymll** [cs2103jan2015-t10-2j/main#36]
so that the user can have a clear view on the to-do tasks

**Comment by jerace23** [comment]
So that the user can be kept up to date.

**Comment by AnshumanMohan** [comment]
can be kept up-to-date, especially about urgent matters

**Comment by anshumanmohan** [comment]
can be kept up-to-date, especially about urgent matters

**Comment by anshumanmohan** [comment]
temporarily closing this because it is not compulsory...
