### ISSUE TITLE
issue a gentle warning when the user tries to add more than 10 tasks in a day. But DO allow the addition.

### ISSUE THREAD

**Issue by ymll** [cs2103jan2015-t10-2j/main#4]
so that the user would not overload

**Comment by jerace23** [comment]
So that the system can imform him/her whether he or she is setting alot of tasks per day

**Comment by anshumanmohan** [comment]
avoid assigning myself too much work in a day

**Comment by anshumanmohan** [comment]
to be done via #106 and #107.

**Comment by anshumanmohan** [comment]
temporarily closing this because it is not compulsory...

**Comment by anshumanmohan** [comment]
temporarily closing this because it is not compulsory...
