### ISSUE TITLE
allow the user to use the "fake ID" to make modifications.

### ISSUE THREAD

**Issue by anshumanmohan** [cs2103jan2015-t10-2j/main#57]
For example:
1. User views in "week view". A list of five things comes up.
2. If the user wants to modify item number 2 (fake ID), he or she can do so by simply hitting something simple like "change 2". 

Alternately: 
1. User searches for a keyword, such as "hippopotamus". All events will "hippopotamus" in the title are displayed.
2. {Same as 2 above}

**Comment by jerace23** [comment]
after viewing the list, can the user just use the alter function instead of change?

**Comment by anshumanmohan** [comment]
Yeah, yeah. Sorry, I used the wrong keyword. But I was proposing that the user should be able to say "alter <fake ID>", instead of the actual ID.

**Comment by anshumanmohan** [comment]
The user should not need to go back to the alter function after finding his or her results. If the results are found, the user should be able to straightaway alter any of the results.

**Comment by jerace23** [comment]
meaning that the user just hit alter command(with their new data) to make changes finding his or her search results? is the same right?

**Comment by jerace23** [comment]
meaning that the user just hit alter command(with their new data) to make changes after finding his or her search results? is the same right?

**Comment by jerace23** [comment]
ok then, since I am doing search class, my job will be showing you fake ids with descriptions. And then your job will be altering those with fake ids(the ones you need to alter)?
