### ISSUE TITLE
Display command usage

### ISSUE THREAD

**Issue by ymll** [cs2103jan2015-t10-2j/main#82]
so that people can learn how to use the system themselves

**Comment by ymll** [comment]
It is better to place the usage message in standard command interface. In this way, it can prevent the usage message not updated to latest version.

**Comment by anshumanmohan** [comment]
Should we hard-code a few helpful messages?
Like if the user types "help add" then a hard-coded dialogue appears, teaching her about Add function.

**Comment by anshumanmohan** [comment]
Same as #21. Close #21.
