### ISSUE TITLE
add additional information for tasks (location, short notes, other attendees, recipient of completed work, etc.)

### ISSUE THREAD

**Issue by ymll** [cs2103jan2015-t10-2j/main#9]
so that the user can remember or understand more about them e.g. notes on a particular task or schedules

**Comment by jerace23** [comment]
So that user will have more details on a particular task

**Comment by anshumanmohan** [comment]
don't forget these details later. 
Note: This feature is ale helpful when sharing the event with other users.

**Comment by anshumanmohan** [comment]
This is already covered in the "description" option.
